const colors = {
  light: {
    text: "#1e1010",
    tint: "#e11d48",
    background: "#fef9fa",
    foreground: "#1e1010",
    card: "#ffffff",
    cardForeground: "#1e1010",
    primary: "#e11d48",
    primaryForeground: "#fafafa",
    secondary: "#f8f0f0",
    secondaryForeground: "#2a1a1a",
    muted: "#f2eeee",
    mutedForeground: "#7a6b6b",
    accent: "#f5ece0",
    accentForeground: "#2a1a1a",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#e4d5d5",
    input: "#e8dcdc",
    success: "#16a34a",
    successForeground: "#ffffff",
    warning: "#d97706",
    warningForeground: "#ffffff",
  },
  dark: {
    text: "#fef9fa",
    tint: "#fb7185",
    background: "#150808",
    foreground: "#fef9fa",
    card: "#2a1212",
    cardForeground: "#fef9fa",
    primary: "#fb7185",
    primaryForeground: "#150808",
    secondary: "#3a2020",
    secondaryForeground: "#fef9fa",
    muted: "#2a1a1a",
    mutedForeground: "#b09090",
    accent: "#3a2a1a",
    accentForeground: "#fef9fa",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#4a2a2a",
    input: "#3a2222",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
  },
  radius: 10,
};

export default colors;
